name: Docker Deploy

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      API_URL: ${{ secrets.API_URL }}
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      BCRYPT_ROUNDS: ${{ secrets.BCRYPT_ROUNDS }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.yml build
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to docker hub
      run: docker-compose -f docker-compose.yml push

